export const STAFFS_LOADING = 'STAFFS_LOADING';
export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const ADD_SINGLE_STAFF = 'ADD_SINGLE_STAFF';
export const UPDATE_STAFF = 'UPDATE_STAFF';
export const DELETE_STAFF = 'DELETE_STAFF';
export const STAFFS_OF_DEPARTMENT = 'STAFFS_OF_DEPARTMENT';
export const STAFFS_SALARY = 'STAFFS_SALARY';

export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const TRANSFER_STAFF_DEPARTMENT = 'TRANSFER_STAFF_DEPARTMENT';